-- MySQL Script generated by MySQL Workbench
-- Wed Sep  9 22:12:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema books_erd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `books_erd` ;

-- -----------------------------------------------------
-- Schema books_erd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `books_erd` DEFAULT CHARACTER SET utf8 ;
USE `books_erd` ;

-- -----------------------------------------------------
-- Table `books_erd`.`dojos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books_erd`.`dojos` ;

CREATE TABLE IF NOT EXISTS `books_erd`.`dojos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books_erd`.`ninjas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books_erd`.`ninjas` ;

CREATE TABLE IF NOT EXISTS `books_erd`.`ninjas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `skill` VARCHAR(45) NULL,
  `dojos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ninjas_dojos_idx` (`dojos_id` ASC) VISIBLE,
  CONSTRAINT `fk_ninjas_dojos`
    FOREIGN KEY (`dojos_id`)
    REFERENCES `books_erd`.`dojos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
